/**
 * embeds.js
 * -----------------------------------------------------
 * Reusable, professionally styled embed builders.
 * Theme: InterENL Store Purple.
 * -----------------------------------------------------
 */

const { EmbedBuilder } = require('discord.js');
const config = require('../config');

/**
 * Applies the shared footer + thumbnail + timestamp to any embed.
 * @param {EmbedBuilder} embed
 * @returns {EmbedBuilder}
 */
function applyBranding(embed) {
    embed.setFooter({ text: config.footer }).setTimestamp();

    if (config.thumbnail) {
        embed.setThumbnail(config.thumbnail);
    }

    return embed;
}

/**
 * Success/primary embed (orange theme).
 * @param {string} title
 * @param {string} [description]
 * @returns {EmbedBuilder}
 */
function successEmbed(title, description = null) {
    const embed = new EmbedBuilder().setColor(config.colors.success).setTitle(`✅ ${title}`);
    if (description) embed.setDescription(description);
    return applyBranding(embed);
}

/**
 * Error embed (red theme) — permission denials, invalid input, failures.
 * @param {string} title
 * @param {string} [description]
 * @returns {EmbedBuilder}
 */
function errorEmbed(title, description = null) {
    const embed = new EmbedBuilder().setColor(config.colors.error).setTitle(`❌ ${title}`);
    if (description) embed.setDescription(description);
    return applyBranding(embed);
}

/**
 * Warning embed (amber theme) — expired/suspended notices.
 * @param {string} title
 * @param {string} [description]
 * @returns {EmbedBuilder}
 */
function warningEmbed(title, description = null) {
    const embed = new EmbedBuilder().setColor(config.colors.warning).setTitle(`⚠️ ${title}`);
    if (description) embed.setDescription(description);
    return applyBranding(embed);
}

/**
 * Neutral black/white informational embed.
 * @param {string} title
 * @param {string} [description]
 * @returns {EmbedBuilder}
 */
function infoEmbed(title, description = null) {
    const embed = new EmbedBuilder().setColor(config.colors.black).setTitle(title);
    if (description) embed.setDescription(description);
    return applyBranding(embed);
}

/**
 * Returns a status-specific emoji + label + color for a license status.
 * @param {string} status
 * @returns {{emoji: string, label: string, color: number}}
 */
function getStatusPresentation(status) {
    switch (status) {
        case 'Active':
            return { emoji: '✅', label: 'Genuine InterENL Store License', color: config.colors.success };
        case 'Expired':
            return { emoji: '⚠️', label: 'License Expired', color: config.colors.warning };
        case 'Suspended':
            return { emoji: '⛔', label: 'License Suspended', color: config.colors.error };
        case 'Revoked':
            return { emoji: '🚫', label: 'License Revoked', color: config.colors.error };
        default:
            return { emoji: '❔', label: 'Unknown Status', color: config.colors.black };
    }
}

/**
 * Formats a license's expiration for display.
 * @param {string|null} expires ISO date string or null for Lifetime.
 * @returns {string}
 */
function formatExpiry(expires) {
    if (expires === null || expires === undefined) return 'Never (Lifetime)';
    return `<t:${Math.floor(new Date(expires).getTime() / 1000)}:F>`;
}

/**
 * Formats any ISO date string for display as a Discord timestamp.
 * @param {string} isoDate
 * @returns {string}
 */
function formatDate(isoDate) {
    if (!isoDate) return 'N/A';
    return `<t:${Math.floor(new Date(isoDate).getTime() / 1000)}:F>`;
}

/**
 * Builds the full license status embed showing every stored field.
 * Used by /license check and /license info.
 * @param {object} license
 * @param {object} [options]
 * @param {boolean} [options.fullInfo] Whether to show extra generation metadata.
 * @returns {EmbedBuilder}
 */
function buildLicenseEmbed(license, { fullInfo = false } = {}) {
    const { emoji, label, color } = getStatusPresentation(license.status);

    const embed = new EmbedBuilder()
        .setColor(color)
        .setTitle(`${emoji} ${label}`)
        .addFields(
            { name: '👤 Owner', value: `${license.username}`, inline: true },
            { name: '🆔 Discord ID', value: `${license.discordID}`, inline: true },
            { name: '📧 Email', value: `${license.email}`, inline: true },
            { name: '🔑 License', value: `\`${license.license}\``, inline: false },
            { name: '📦 Plan', value: `${license.plan}`, inline: true },
            { name: '📅 Created', value: formatDate(license.created), inline: true },
            { name: '⏳ Expires', value: formatExpiry(license.expires), inline: true },
            { name: '📊 Status', value: `${license.status}`, inline: true },
            { name: '🛠️ Generated By', value: `<@${license.generatedBy}>`, inline: true }
        );

    if (fullInfo) {
        embed.addFields(
            { name: '🕒 Generation Timestamp', value: formatDate(license.generatedAt), inline: true },
            { name: '📝 Suspend Reason', value: license.suspendReason || 'N/A', inline: true }
        );
    }

    return applyBranding(embed);
}

/**
 * Renders a text progress bar, e.g. "████████░░░░░░░░ 50%".
 * @param {number} current
 * @param {number} max
 * @param {number} [length=16] Number of block characters.
 * @returns {string}
 */
function buildProgressBar(current, max, length = 16) {
    const safeMax = max > 0 ? max : 1;
    const ratio = Math.max(0, Math.min(1, current / safeMax));
    const filled = Math.round(ratio * length);
    const bar = '█'.repeat(filled) + '░'.repeat(length - filled);
    return `${bar} ${Math.round(ratio * 100)}%`;
}

module.exports = {
    applyBranding,
    successEmbed,
    errorEmbed,
    warningEmbed,
    infoEmbed,
    getStatusPresentation,
    formatExpiry,
    formatDate,
    buildLicenseEmbed,
    buildProgressBar
};
